# Generated by Django 4.2.3 on 2023-08-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_match_home_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='body_part',
            field=models.CharField(choices=[('Foot', 'Foot'), ('Head', 'Head'), ('Left Foot', 'Left Foot'), ('Right Foot', 'Right Foot')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shot',
            name='body_part',
            field=models.CharField(choices=[('Foot', 'Foot'), ('Head', 'Head'), ('Left Foot', 'Left Foot'), ('Right Foot', 'Right Foot')], max_length=10),
        ),
    ]
