# Generated by Django 4.2.3 on 2023-08-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='overall',
            field=models.IntegerField(default=0),
        ),
    ]
