# Generated by Django 4.2.3 on 2023-08-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_player_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='overall',
            field=models.IntegerField(),
        ),
    ]
