from django import forms
from tracker.models.player import Player
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Div


class CreateShotForm(forms.Form):
    
    def __init__(self, team, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['player'].queryset = Player.objects.filter(team=team)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('minute', css_class='col-4'),
                Column('body_part', css_class='col-4'),
                Column('player', css_class='col-4')
            ),
            Row(
                Column('corner', css_class='col-4'),
                Column('on_target', css_class='col-4'),
                Column('blocked_by_player', css_class='col-4'),
            ) 
        )
    
    minute = forms.IntegerField()
    corner = forms.BooleanField(required=False, label='Generated by Last Corner')
    on_target = forms.BooleanField(required=False)
    blocked_by_player = forms.BooleanField(required=False, label='Blocked by Position Player')
    body_part = forms.ChoiceField(choices=[('Foot', 'Foot'), ('Head', 'Head')])
    player = forms.ModelChoiceField(queryset=Player.objects.all())